version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CFG_LISTENERS: PLAINTEXT
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "first_topic:1:3"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    depends_on:
      - kafka
  authentication:
    image: authentication:0.1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

